# Generated by Django 3.2.7 on 2021-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_options_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('radio', 'radio'), ('text', 'text')], default=('checkbox', 'checkbox'), max_length=8),
        ),
    ]
